#!/usr/bin/env bash
# Regenerates the WASM bridge and vendors its output into packages/xlsx, which is what
# ships to npm consumers — they don't have a Rust/wasm-pack toolchain, so the compiled
# artifact must be committed there, not built on the fly (this matches common practice
# for wasm-bindgen-based npm packages). crates/elixcee-wasm/pkg-node and pkg-web
# themselves are wasm-pack's own build output (gitignored via their own generated
# .gitignore — see git status), regenerated by this script on demand; only their copies
# under packages/xlsx/src/internal/wasm/ are committed.
#
# Run this after any change to crates/elixcee-wasm/src or crates/elixcee-types/src (or
# src/reader.rs, which elixcee-wasm depends on transitively) that should reach
# @elixcee/xlsx's XLSX.read().
set -euo pipefail
cd "$(dirname "$0")"

wasm-pack build --target nodejs --out-dir pkg-node --out-name elixcee_wasm
wasm-pack build --target web --out-dir pkg-web --out-name elixcee_wasm
node build-browser-inline.mjs

dest=../../packages/xlsx/src/internal/wasm
mkdir -p "$dest"
cp pkg-node/elixcee_wasm.js "$dest/elixcee_wasm.node.cjs"
cp pkg-node/elixcee_wasm_bg.wasm "$dest/elixcee_wasm_bg.wasm"
cp pkg-web/elixcee_wasm.inline.mjs "$dest/elixcee_wasm.browser.mjs"

echo "vendored WASM bridge into $dest:"
ls -la "$dest"
