[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "MIT",
  "Unlicense",
  "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
